export class Employee {
    username: string = '';
    password: string = '';
    firstName: string = '';
    lastName: string = '';
    _id: number = 0;
    index: number = 0;
    guid: string = '';
    isActive: boolean = false;
    balance: number = 0;
    picture: string = '';
    age: number = 0;
    eyeColor: string = '';
    name: string = '';
    gender: string = '';
    company: string = '';
    email: string = '';
    phone: string = '';
    address: string = '';
    registered: string = Date.now().toLocaleString();
}